export default {
  'zh-CN': {
    pageTitle: 'Road治理',
    title: '参与ROAD通证方案投票<span>瓜分50,000ROAD奖励</span>',
    desc: '为更好地促进ROAD生态，提升通证价值，ROAD计划实施新的通证方案，希望获得社区用户的支持，请您投出宝贵的一票！',
    newVotes: '{num} 票',
    oldVotes: '{num} 票',
    newName: '新通证',
    oldName: '原通证',
    voteTip: '您已于 {time} 投给{type} {num} {currency}',
    lockedPosition: '永久锁仓：',
    lockedPositionNum: '15亿',
    initialPosition: '初期流通：',
    fundPosition: '基金团队：',
    initialPositionNum: '2亿',
    teamPosition: '团队：',
    teamPositionNumOld: '2亿',
    teamPositionNumNew: '5000万',
    communityPosition: '生态系统：',
    communityPositionNumOld: '14亿',
    communityPositionNumNew: '2.5亿',
    communityPositionTipOld: '（计划2022年启动挖矿）',
    communityPositionTipNew: '（计划2022年6月启动挖矿，具体方案由社区决定）',
    voteUse: '使用：',
    voteName: '投票',
    votePlaceholder: '请输入投票数量',
    votePleaseChoose: '请选择投票币种',
    votePleaseInputCorrect: '请输入正确的投票数量',
    voteNumExceedBalance: '投票数超过余额',
    voteSuccess: '投票成功',
    balanceAvailable: '可用额度：',
    ruleExplain: '规则<span class="title-x"></span>说明',
    ruleInfo1: '1、1枚ROAD=1票，1枚MX=1票，最低1票起投，无投票上限。投票期间，每位用户仅能投票1次，不可多次投票。',
    ruleInfo2: '2、所有参与投票的用户，投票结束后可根据投票数量占比参与瓜分50,000ROAD奖励。',
    ruleInfo3: '3、如果投票提案通过，ROAD项目团队将于2020年9月28日执行新通证方案。',
    ruleInfo4: '4、参与投票的ROAD和MX不会冻结。',
    projectExplain: '项目<span class="title-x"></span>介绍',
    projectExplainText: '项目介绍',
    projectExplainInfo:
      '汽车账本是汽车全生命周期的交互和记账系统，汽车账本的构建、增量、拓展依赖于ROAD商业应用的构建、增量和拓展。汽车账本将 成为5G通信和人工智能时代的基础设施。ROAD TOKEN是贯穿所有协议、应用、商业的通证，我们期望在5G通信和人工智能时代，打造区块链领域的交通银行。',
    projectPlan: '项目规划',
    projectPlanInfo1: '2019年 Q2，ROAD 团队组建，ROAD产品与商业模式成形，开发OBD挖矿设备;',
    projectPlanInfo2: '2019年 Q3，ROAD 底层技术架构确定，OBD设备开发完成，开发汽车账本APP1.0;',
    projectPlanInfo3: '2019年 Q4, 汽车账本 1.0 APP 推出，OBD设备开始销售;',
    projectPlanInfo4: '2020年 Q1-Q3，汽车账本用户达到10万人，和国内知名新造车达成合作，植入汽车账本;',
    projectPlanInfo5: '2020年 Q3-Q4，智能语音挖矿行车记录仪推出，同国内汽车后设备厂家达成合作，汽车账本活跃用户超过50万人;',
    projectPlanInfo6:
      '2021-2022年，和更多汽车厂商达成合作，形成开发者联盟,更多基于ROAD的汽车后市场的DAPP出现，推动国内5G车联网区块链开放联盟，ROAD商业生态成熟，推出汽车数据交易产品 1.0。',
    projectLightSpot: '项目亮点',
    projectLightSpotInfo:
      'ROAD是基于汽车账本的分布式车联网经济系统，是一个基于商业驱动的车联网区块链项目，以自主研发的5G OBD硬件设备为基础，打造了核心产品汽车账本，瞄准全球汽车及售后市场，服务市场。ROAD用区块链技术重构车联网，以优化全球13亿部存量车的网络交互方式为目标，实现汽车数据价值化，检修服务自动化等一系列价值生态落地。',
    projectProgress: '开发进度',
    projectProgressInfo:
      '目前已经完成ROAD底层技术架构：数据生产层(包括采集和提交);数据存储层(包括数据和交易的验证，海量数据的分布式存储和交易记录以及关键数据的链上存储);以及应用层(包括数据发布，搜索和计算，用户应用)的搭建成功推出汽车账本1.0APP，开始销售OBD设备。',
    projectUse: '通证使用场景',
    projectUseInfo:
      'ROAD基于商业模式驱动，通过商业应用的拓展和进化，不断丰富汽车账本的数据价值和交互价值。ROAD通证使用场景包括汽车档案记载、智能驾驶、汽车养护、汽车金融、电子商务、共享用车等。同时，存量汽车进行5G联网改造也是ROAD未来非常重要的商业应用。'
  },
  'zh-TW': {
    pageTitle: 'Road治理',
    title: '參與ROAD通證方案投票<span>瓜分50,000ROAD獎勵</span>',
    desc: '為更好地促進ROAD生態，提升通證價值，ROAD計劃實施新的通證方案，希望獲得社區用戶的支持，請您投出寶貴的一票！',
    newVotes: '{num} 票',
    oldVotes: '{num} 票',
    newName: '新通證',
    oldName: '原通證',
    voteTip: '您已於 {time} 投給{type} {num} {currency}',
    lockedPosition: '永久鎖倉：',
    lockedPositionNum: '15億',
    initialPosition: '初期流通：',
    fundPosition: '基金團隊：',
    initialPositionNum: '2億',
    teamPosition: '團隊：',
    teamPositionNumOld: '2億',
    teamPositionNumNew: '5000萬',
    communityPosition: '生態系統：',
    communityPositionNumOld: '14億',
    communityPositionNumNew: '2.5億',
    communityPositionTipOld: '（計劃2022年啟動挖礦）',
    communityPositionTipNew: '（計劃2022年6月啟動挖礦，具體方案由社區決定）',
    voteUse: '使用：',
    voteName: '投票',
    votePlaceholder: '請輸入投票數量',
    votePleaseChoose: '請選擇投票幣種',
    votePleaseInputCorrect: '請輸入正確的投票數量',
    voteNumExceedBalance: '投票數超過餘額',
    voteSuccess: '投票成功',
    balanceAvailable: '可用額度：',
    ruleExplain: '規則<span class="title-x"></span>說明',
    ruleInfo1: '1、1枚ROAD=1票，1枚MX=1票，最低1票起投，無投票上限。投票期間，每位用戶僅能投票1次，不可多次投票。',
    ruleInfo2: '2、所有參與投票的用戶，投票結束後可根據投票數量佔比參與瓜分50,000ROAD獎勵。',
    ruleInfo3: '3、如果投票提案通過，ROAD項目團隊將於2020年9月28日執行新通證方案。',
    ruleInfo4: '4、參與投票的ROAD和MX不會凍結。',
    projectExplain: '項目<span class="title-x"></span>介紹',
    projectExplainText: '項目介紹',
    projectExplainInfo:
      '汽車賬本是汽車全生命週期的交互和記賬系統，汽車賬本的構建、增量、拓展依賴於ROAD商業應用的構建、增量和拓展。汽車賬本將 成為5G通信和人工智能時代的基礎設施。 ROAD TOKEN是貫穿所有協議、應用、商業的通證，我們期望在5G通信和人工智能時代，打造區塊鏈領域的交通銀行。',
    projectPlan: '項目規劃',
    projectPlanInfo1: '2019年 Q2，ROAD 團隊組建，ROAD產品與商業模式成形，開發OBD挖礦設備;',
    projectPlanInfo2: '2019年 Q3，ROAD 底層技術架構確定，OBD設備開發完成，開發汽車賬本APP1.0;',
    projectPlanInfo3: '2019年 Q4, 汽車賬本 1.0 APP 推出，OBD設備開始銷售;',
    projectPlanInfo4: '2020年 Q1-Q3，汽車賬本用戶達到10萬人，和國內知名新造車達成合作，植入汽車賬本;',
    projectPlanInfo5: '2020年 Q3-Q4，智能語音挖礦行車記錄儀推出，同國內汽車後設備廠家達成合作，汽車賬本活躍用戶超過50萬人;',
    projectPlanInfo6:
      '2021-2022年，和更多汽車廠商達成合作，形成開發者聯盟,更多基於ROAD的汽車後市場的DAPP出現，推動國內5G車聯網區塊鏈開放聯盟，ROAD商業生態成熟，推出汽車數據交易產品1.0。',
    projectLightSpot: '項目亮點',
    projectLightSpotInfo:
      'ROAD是基於汽車賬本的分佈式車聯網經濟系統，是一個基於商業驅動的車聯網區塊鏈項目，以自主研發的5G OBD硬件設備為基礎，打造了核心產品汽車賬本，瞄準全球汽車及售後市場，服務市場。ROAD用區塊鏈技術重構車聯網，以優化全球13億部存量車的網絡交互方式為目標，實現汽車數據價值化，檢修服務自動化等一系列價值生態落地。',
    projectProgress: '開發進度',
    projectProgressInfo:
      '目前已經完成ROAD底層技術架構：數據生產層(包括採集和提交);數據存儲層(包括數據和交易的驗證，海量數據的分佈式存儲和交易記錄以及關鍵數據的鏈上存儲);以及應用層(包括數據發布，搜索和計算，用戶應用)的搭建成功推出汽車賬本1.0APP，開始銷售OBD設備。',
    projectUse: '通證使用場景',
    projectUseInfo:
      'ROAD基於商業模式驅動，通過商業應用的拓展和進化，不斷豐富汽車賬本的數據價值和交互價值。 ROAD通證使用場景包括汽車檔案記載、智能駕駛、汽車養護、汽車金融、電子商務、共享用車等。同時，存量汽車進行5G聯網改造也是ROAD未來非常重要的商業應用。 '
  },
  'en-US': {
    pageTitle: 'Road Governance',
    title: 'Join ROAD Token Proposal Voting <span> to Share 50,000 ROAD Rewards</span>',
    desc:
      'In order to better promote the ROAD ecosystem and enhance the value of the ROAD token, ROAD project party plans to implement a new token scheme and hopes to get the support of community users, please vote for it!',
    newVotes: '{num} votes',
    oldVotes: '{num} votes',
    newName: 'The new token',
    oldName: 'The original token',
    voteTip: 'You haved vote for {type} {num} {currency} at  {time}',
    lockedPosition: 'Permanent lock-up:',
    lockedPositionNum: '1.5 billion',
    initialPosition: 'Initial circulation:',
    fundPosition: 'Fund team:',
    initialPositionNum: '200 million',
    teamPosition: 'Team:',
    teamPositionNumOld: '200 million',
    teamPositionNumNew: '50 million',
    communityPosition: 'Ecosystem:',
    communityPositionNumOld: '1.4 billion',
    communityPositionNumNew: '250 million',
    communityPositionTipOld: '(Mining will start in 2022)',
    communityPositionTipNew: '(Mining will start in June, 2020 and the specific details will be determined by the community)',
    voteUse: 'Use:',
    voteName: 'Vote',
    votePlaceholder: 'Please enter the number of votes',
    votePleaseChoose: 'Please select the voting coin',
    votePleaseInputCorrect: 'Please enter the correct number of votes',
    voteNumExceedBalance: 'The number of votes exceeds the balance',
    voteSuccess: 'Vote successful',
    balanceAvailable: 'Available amount:',
    ruleExplain: 'Rule <span class="title-x"></span> Description',
    ruleInfo1:
      '1. 1 ROAD = 1 vote, 1 MX = 1 vote, the minimum amount is 1 vote, and no hard cap for voting. During the voting period, each user can only vote once and cannot vote multiple times.',
    ruleInfo2: '2. All users who participated in the voting can share 50,000 ROAD rewards in  proportion to votes after the voting ends.',
    ruleInfo3: '3. If the voting proposal is passed, the ROAD project team will implement the new token scheme on September 28, 2020.',
    ruleInfo4: '4. ROAD and MX participating in voting will not be frozen.',
    projectExplain: 'Project <span class="title-x"></span> introduction',
    projectExplainText: 'Project Introduction',
    projectExplainInfo:
      'The auto-ledger is a interaction and accounting system for the full life cycle of the automobile. We believe that it will become an infrastructure for automobile industry in the 5G communications and artificial intelligence era.',
    projectPlan: 'Project Roadmap',
    projectPlanInfo1: 'In 2019, Q2, build up ROAD team, form ROAD products and business models, and develop OBD mining equipment;',
    projectPlanInfo2:
      'In 2019, Q3, define the underlying technical architecture of ROAD, complete development of OBD equipment and the development of auto-ledger APP1.0;',
    projectPlanInfo3: 'In Q2019, Q4, launch auto-ledger 1.0 APP, and sales the OBD equipment;',
    projectPlanInfo4:
      'In 2020 Q1-Q3, the number of users of auto-ledger reached 100,000, and reached a cooperation with well-known Chinese new car manufacturer, embed the auto-ledger in new manufactured cars;',
    projectPlanInfo5:
      'In 2020, Q3-Q4, launch the intelligent voice mining driving recorder was launched, and the domestic automobile after-equipment manufacturers reached a cooperation. The auto account book has more than 500,000 active users, and the ROAD-based car maintenance, used car trading, auto-finance and other businesses have formed a certain share;',
    projectPlanInfo6:
      'In 2021-2022, cooperation with more auto manufacturers to form a developer alliance, more ROAD-based automotive DAPP emerged, promote the China 5G Internet of vehicle blockchain open alliance and ROAD business ecology mature, launch automotive data trading product version1.0.',
    projectLightSpot: 'Project Highlights',
    projectLightSpotInfo:
      'ROAD is a distributed Internet of Vehicles economic system based on the auto ledger. It is a business-driven Internet of Vehicles blockchain project. Based on the self-developed 5G OBD hardware equipment, it has created the core product auto ledger, targeting the global automobile and after-sales market , service market. ROAD uses blockchain technology to reconstruct the Internet of Vehicles, with the goal of optimizing the network interaction mode of 1.3 billion vehicles in the world, and realizes the realization of a series of value ecology such as the value of automobile data and the automation of maintenance services.',
    projectProgress: 'Development Progress',
    projectProgressInfo:
      'The underlying technical architecture of ROAD has been completed: data production layer (including collection and submission); data storage layer (including data and transaction verification, distributed storage of massive data and transaction records, and on-chain storage of key data); and application layer (Including data release, search and calculation, user applications) successfully launched Auto Ledger 1.0 APP, and started selling OBD devices.',
    projectUse: 'Token Usage',
    projectUseInfo:
      'ROAD is driven by a business model and continuously enriches the data value and interactive value of the car ledger through the expansion and evolution of business applications. The usage scenarios of the ROAD pass include car file records, intelligent driving, car maintenance, auto finance, e-commerce, shared cars, etc. At the same time, the 5G networking transformation of stock cars is also a very important commercial application for ROAD in the future.'
  }
};
